name: Enhancement Request
description: Request for additional content or a change to existing content in the workshop
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
