name: Test - Networking

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 3"

permissions:
  id-token: write
  contents: read

jobs:
  test-module:
    uses: ./.github/workflows/module-test.yaml
    with:
      glob: networking/vpc-cni**
    secrets: inherit
  test-lattice:
    uses: ./.github/workflows/module-test.yaml
    with:
      module: networking/vpc-lattice
    secrets: inherit
